// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class admin_guncellememig1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(admin_guncellememig1));
        
        string IMigrationMetadata.Id
        {
            get { return "202309261623454_admin_guncelleme-mig1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
