// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class admin_guncelleme_mig2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(admin_guncelleme_mig2));
        
        string IMigrationMetadata.Id
        {
            get { return "202309261631406_admin_guncelleme_mig2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
