// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class adding_adminrole_mig11 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adding_adminrole_mig11));
        
        string IMigrationMetadata.Id
        {
            get { return "202310082224201_adding_adminrole_mig11"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
